name: Lint
on:
  push:
    branches-ignore:
      - master
jobs:
  lint-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Install frontend modules
        run: npm ci
      - name: Lint frontend
        run: npm run lint:prod
      - name: Install backend modules
        run: cd api && pip install -r requirements.txt && pip install pylint
      - name: Lint backend
        run: cd api && python -m pylint *.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[Github Actions] lint files"
